### PR TITLE
Russian Localization Improvements

### PR DESCRIPTION
**Pull request by userNameIsBoris**
Hi! I improved the RU localization. 

**I think bd667911b63c8a399cb9b4cb5574209449d2ef9c worth explaining in more details:** 
Apple uses guillemets quotation marks («…») throughout the RU system localization, so now the app's localization follows the system-wide style.

Peace!

### CODE REVIEW

**Comment by tladesignz** [comment]
This is awesome, thank you!

However, we're organizing localizations at Transifex: https://www.transifex.com/otf/onion-browser/dashboard/

I will most probably continue to accept your pull requests, but it would be way better if you'd join that platform and apply as translator for our project there, so you can coordinate and evtl. discuss changes with your fellow translators and Localization Labs, who help us organize all translation efforts.

**Comment by tladesignz** [comment]
(And you're invited to contribute to other projects, as well, of course, e.g. like [Orbot](https://orbot.app)!

**Comment by userNameIsBoris** [comment]
> However, we're organizing localizations at Transifex: https://www.transifex.com/otf/onion-browser/dashboard/

Got it, thanks! I sent the join request at Transifex and will be happy to improve other translations. 🙂

**Comment by yeyeyeyeyyeyeyeyey** [comment]
Great! Thanks!

**Pull request merged**
