### PR TITLE
Fix issue #128: Pull in latest Endless changes.

### PR DESCRIPTION
**Pull request by tladesignz**
Mike, please review this, as I'm not totally sure, if I didn't kill one of your patches!

### CODE REVIEW

**Comment by basebandlove** [comment]
This fixes the bottom but not the top.

**Review by mtigas — CHANGES_REQUESTED** [review]
Looks good to me overall, but I do notice that on a fresh install and on the first run, the app gets stuck on the "connecting..." scene even though Tor finishes making the connection. (Never shows "Start Browsing".) That loading progress bar doesn't update at all (stays fully gray) too.

Any app launch after that point seems to work. And other than the above, it seems good (Tor works, basic stuff that I tested works).

Rolling back to the current 2.X, things seem fine. So there's some regression in there, probably some delegate that's not hooked up properly anymore.

**Comment by tladesignz** [comment]
The mentioned issue is in upstream, too. It's only visible, when the first connection is slow enough, that the user makes it through to the "connecting..." scene, while Tor startup isn't finished, yet.

I fixed it. Great, that you spotted it!

**Comment by ingfabby** [comment]
Hi,

This is from the Apple store account, I just want to make sure you know about this:
Upcoming Submission Requirements
As a reminder, starting March 27, 2019 all new apps and app updates for iPhone or iPad, including universal apps, will need to be built with the iOS 12.1 SDK and support iPhone XS Max or the 12.9-inch iPad Pro (3rd generation). Screenshots for these devices will also be required. All new apps and app updates for Apple Watch will need to be built with the watchOS 5.1 SDK and support Apple Watch Series 4. 
Also, we have this suggestion " Any chance to expand search engine selections to include Qwant would be great" from a user rating the app with 5 stars on the Apple Store, and before I reply thanking him for his support I would like to know how to reply to his suggestion.
Thanks

**Comment by tladesignz** [comment]
Thanks @ingfabby!

Apple sends mails with content like that. We're already compatible, son no worries.

**Comment by ingfabby** [comment]
Awesome,  thanks for letting me know Benjamin.

**Comment by ingfabby** [comment]
Hi,
We have this report from a user on the Apple App store today:
"The latest update to the Onion Browser fails to confirm connection to the TOR network, giving an error message instead.  Therefore, it cannot be trusted.  So I’ve deleted it."

**Comment by ingfabby** [comment]
We also got this yesterday:
"Captchas don’t work anymore. Thank you for updating, I thought you forgot about the app, but now captchas don’t work, can you fix. Didn’t have to enable JavaScript. Please, It was a 5 star app, the only one on IOS, but there really isn’t a tor on IOS so IOS is not Tor-friendly at all"

**Comment by tladesignz** [comment]
@ingfabby, you're commenting on a closed pull request.
Please, don't do that, this is not the right spot for conversations about issues not related to that pull request.

Regarding your first comment: I guess, that's a variation on #164. That's an issue server-side already fixed by @mtigas.

Regarding your second comment: You created issue #166 for this. Please follow up there.

**Comment by ingfabby** [comment]
Yes, I realized my mistake after l posted my comment and created the ticket
right after, I'm sorry.

Thanks Benjamin.

**Pull request merged**
